services:
  paperlessbroker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - /opt/docker/volumes/redisdata:/data
  paperlessdb:
    image: docker.io/library/postgres:18
    restart: unless-stopped
    volumes:
      - /opt/docker/volumes/pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: paperlessdb
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
  paperlesswebserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - paperlessdb
      - paperlessbroker
    ports:
      - "8010:8000"
    volumes:
      - /opt/docker/volumes/data:/usr/src/paperless/data
      - /opt/docker/volumes/media:/usr/src/paperless/media
      - /opt/docker/volumes/export:/usr/src/paperless/export
      - /opt/docker/volumes/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://paperlessbroker:6379
      PAPERLESS_DBHOST: paperlessdb
    env_file:
      - stack.env
volumes:
  data:
  media:
  pgdata:
  redisdata: